FROM ubuntu:latest

RUN apt update && apt upgrade -y && apt install python3 -y && apt install python3-opencv -y && apt install ffmpeg -y && apt install python3-pip -y && apt install git -y && apt autoremove -y

RUN git clone https://github.com/Agustinm28/Computacion_2.git

WORKDIR /Computacion_2/Final

COPY data data

RUN pip3 install -r requirements.txt

CMD ["python3", "pixy_client.py"]